feat(*) add network mode
Kong/gojira pull request #14
Opened 2021-02-02 17:55 UTC by eskerda

This PR adds the possibility of setting up `network-mode`:

If set to `host`, it will remove all docker network isolation, and any service will bind ports locally.

This is going to be useful to run extra services easier, run the grpc specs, also for a very common usecase which is using only one `gojira` setup at the same time.

2021-02-02 17:57 UTC, eskerda commented
The alternative implementation is:
- set `network_mode` only on the target container (kong).
- bind other container ports to localhost (or randomly allocated ports?).
- keep other containers on their own isolated network.

2021-02-03 20:39 UTC, mikefero requested changes
Looks good, just a couple of comments.

**Note**: I was able to test this using a local 3-node Cassandra cluster and things were working great; nice job.

### Starting gojira
```
KONG_DATABASE=cassandra \
KONG_TEST_DATABASE=cassandra \
  gojira up \
         --network-mode host \
         --alone \
         -e KONG_CASSANDRA_REPL_FACTOR=3 \
         -e KONG_CASSANDRA_WRITE_CONSISTENCY=QUORUM \
         -e KONG_CASSANDRA_READ_CONSISTENCY=QUORUM \
         -e KONG_DB_UPDATE_PROPAGATION=30
```

### C* keyspace configuration
#### Command
```
describe keyspace kong;
```
#### Output
```
CREATE KEYSPACE kong WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

.
.
.
```

2021-02-03 21:17 UTC, eskerda commented on gojira.sh
> +        GOJIRA_NETWORK_MODE=$2
I do not follow. `none` is a valid network mode for docker, why not allow it?

2021-02-03 21:38 UTC, mikefero commented on gojira.sh
> +        GOJIRA_NETWORK_MODE=$2
yeah I just didn't think it would be something wanted with gojira; I am fine with the check or without it,

2021-02-03 21:39 UTC, mikefero approved these changes

2021-02-04 11:23 UTC, merged